export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_LOADING = 'SET_LOADING';
export const SET_SIGNUP_ERROR = 'SET_SIGNUP_ERROR';
export const SET_FORGOT_PASSWORD_ERROR = 'SET_FORGOT_PASSWORD_ERROR';
export const SET_ERROR = 'SET_ERROR';
export const USER_DETAIL ='USER_DETAIL';
export const FORGET_PASSWORD='FORGET_PASSWORD';
export const RESET_PASSWORD='RESET_PASSWORD';
export const SET_LOGOUT='SET_LOGOUT';
export const AUTH_LOADING='AUTH_LOADING';
export const AUTH_SIGNUP_LOADING='AUTH_SIGNUP_LOADING'

export const SET_VEGGIES='SET_VEGGIES';
export const SET_FRUITS='SET_FRUITS';
export const SET_EXOTIC='SET_EXOTIC';
export const SET_FRESH_CUT='SET_FRESH_CUT';
export const SET_BUNDLES='SET_BUNDLES';
export const PRODUCT_LOADER='PRODUCT_LOADER';

export const SET_ORDERS='SET_ORDERS';
export const SET_NOTIFICATIONS='SET_NOTIFICATIONS';
export const SET_FINAL_ORDER = 'SET_FINAL_ORDER';
export const ORDER_LOADING='ORDER_LOADING';
export const NOTIFICATION_LOADING='NOTIFICATION_LOADING';

export const SET_SLIDER='SET_SLIDER';
export const HOME_LOADING='HOME_LOADING'

export const SET_CART='SET_CART';
export const SET_STOCK_VEGGIES='SET_STOCK_VEGGIES';
export const SET_STOCK_FRUITS='SET_STOCK_FRUITS';
export const SET_STOCK_EXOTIC='SET_STOCK_EXOTIC';
export const SET_STOCK_FRESH_CUT='SET_STOCK_FRESH_CUT';
export const SET_STOCKS='SET_STOCKS';
export const SET_SUBMIT_ORDER_RESP='SET_SUBMIT_ORDER_RESP';
export const SET_ORDER_ITEMS='SET_ORDER_ITEMS';
export const SET_PROMO_CODE='SET_PROMO_CODE';
export const SET_SUBMIT_CART_LOADING='SET_SUBMIT_CART_LOADING';

export const  SET_ORDER_MODAL='SET_ORDER_MODAL';